---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstnetmicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: sam12302021/firstnetmicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: firstnetmicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: firstnetmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: firstnetmicroservice