@TodoApp.Api_HostAddress = http://localhost:5141

### GET All Todos
GET http://localhost:5141/api/todo
Accept: application/json

### Post a Todo
POST http://localhost:5141/api/todo
Content-Type: application/json
Accept: application/json

{
    "Title": "Adding the sixth Todo",
    "IsCompleted": true
}

### Get a Todo by ID
GET http://localhost:5141/api/todo/3
Accept: application/json


### Delete a Todo
DELETE http://localhost:5141/api/todo/4
Accept: application/json


### Update a Todo
PUT  http://localhost:5141/api/todo/3
Content-Type: application/json
Accept: application/json

{
    "Title": "Adding the thirty-third Todo",
    "IsCompleted": true
}